source "$HOME/.config/shell/general_aliases.sh"
source "$HOME/.config/shell/flutter_aliases.sh"
source "$HOME/.config/shell/navigation_aliases.sh"
source "$HOME/.config/shell/search_functions.sh"
source "$HOME/.config/shell/purge/purge.sh"
source "$HOME/.config/shell/android/android.sh"
