# Fish aliases kept outside mise activation so shell startup can use mise shims only.

alias fishconfig='nvim ~/.config/fish/config.fish'
alias v='nvim'
alias sourcefish='source ~/.config/fish/config.fish'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias ls='eza -l --icons=always -m -n -l'
alias la='eza -la --icons=always -m -n -l'
alias l='eza -la --icons=always -m -n -l'
alias ll='eza -l --icons=always -m -n -l'
alias lt='eza --tree --icons=always'

alias mkdir='mkdir -p'
alias firebase='firebase-tools'

alias dbb='flutter clean && dart run build_runner build -d'
alias dbw='flutter clean && dart run build_runner watch -d'
function mbf
    mason make feature_brick --project_name (awk 'NR==1 {print $2; exit}' pubspec.yaml) --name $argv
end

alias cea='npx create-expo-app@latest'
alias cea-blk='npx create-expo-app@latest --template blank-typescript'

alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gbD='git branch --delete --force'
alias gbnm='git branch --no-merged'
alias gbr='git branch --remote'
alias gbg='LANG=C git branch -vv | grep ": gone\]"'
alias gco='git checkout'
alias gcor='git checkout --recurse-submodules'
alias gcb='git checkout -b'
alias gcB='git checkout -B'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gclean='git clean --interactive -d'
alias gcl='git clone --recurse-submodules'
alias gclf='git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules'
alias gcmsg='git commit --message'
alias gd='git diff'
alias gfo='git fetch origin'
alias ghh='git help'
alias glgg='git log --graph'
alias gf='git fetch'
alias gm='git merge'
alias gmtl='git mergetool --no-prompt'
alias gmtlvim='git mergetool --no-prompt --tool=vimdiff'
alias gl='git pull'
alias gpr='git pull --rebase'
alias gp='git push'
alias gpd='git push --dry-run'
alias gst='git status'
alias gsw='git switch'
alias gswc='git switch --create'
alias grf='git reflog'
alias gr='git remote'
alias grv='git remote --verbose'
alias gra='git remote add'
alias grrm='git remote remove'
alias grmv='git remote rename'
alias grset='git remote set-url'
alias grup='git remote update'
alias grh='git reset'
alias gru='git reset --'
alias grhh='git reset --hard'
alias grhk='git reset --keep'
alias grhs='git reset --soft'
alias grs='git restore'
alias grss='git restore --source'
alias grst='git restore --staged'
alias grev='git revert'
alias greva='git revert --abort'
alias grevc='git revert --continue'
alias grm='git rm'
alias grmc='git rm --cached'
alias gstall='git stash --all'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'

alias gwn='mise run wt:new'
alias gwr='mise run wt:remove'
alias gwri='mise run wt:remove_interactive'
alias gwl='wt list'
alias gws='wt switch'
alias gwm='wt merge'
alias glg='lazygit'

function ghwho
    echo (git config user.name)' <'(git config user.email)'>'
end
alias ghsw='gh auth switch'
alias ghst='gh auth status'

alias ba='brew autoremove'
alias bcfg='brew config'
alias bci='brew info --cask'
alias bcin='brew install --cask'
alias bcl='brew list --cask'
alias bcn='brew cleanup'
alias bco='brew outdated --cask'
alias bcrin='brew reinstall --cask'
alias bcubc='brew upgrade --cask && brew cleanup'
alias bcubo='brew update && brew outdated --cask'
alias bcup='brew upgrade --cask'
alias bdr='brew doctor'
alias bfu='brew upgrade --formula'
alias bi='brew install'
alias bih='brew install --HEAD'
alias bl='brew list'
alias bo='brew outdated'
alias br='brew reinstall'
alias brewp='brew pin'
alias brewsp='brew list --pinned'
alias brh='brew reinstall --HEAD'
alias bs='brew search'
alias bsl='brew services list'
alias bsoff='brew services stop'
alias bsoffa='bsoff --all'
alias bson='brew services start'
alias bsona='bson --all'
alias bsr='brew services run'
alias bsra='bsr --all'
alias bu='brew update'
alias bubo='brew update && brew outdated'
alias bubu='bubo && bup'
alias bubug='bubo && bugbc'
alias bugbc='brew upgrade --greedy && brew cleanup'
alias bup='brew upgrade'
alias buz='brew uninstall --zap'

alias fl='flutter'
alias flattach='flutter attach'
alias flb='flutter build'
alias flchnl='flutter channel'
alias flc='flutter clean'
alias fldvcs='flutter devices'
alias fldoc='flutter doctor'
alias flpub='flutter pub'
alias flget='flutter pub get'
alias flr='flutter run'
alias flrd='flutter run --debug'
alias flrp='flutter run --profile'
alias flrr='flutter run --release'
alias flupgrd='flutter upgrade'

alias nu='nest update'
alias nnew='nest new'
alias nb='nest build'
alias ns='nest start'
alias nsw='nest start --watch'
alias nsd='nest start --dev'
alias nsdbg='nest start --debug --watch'
alias ni='nest info'

alias dco='docker compose'
alias dcb='docker compose build'
alias dce='docker compose exec'
alias dcps='docker compose ps'
alias dcrestart='docker compose restart'
alias dcrm='docker compose rm'
alias dcr='docker compose run'
alias dcstop='docker compose stop'
alias dcup='docker compose up'
alias dcupb='docker compose up --build'
alias dcupd='docker compose up -d'
alias dcupdb='docker compose up -d --build'
alias dcdn='docker compose down'
alias dcl='docker compose logs'
alias dclf='docker compose logs -f'
alias dclF='docker compose logs -f --tail 0'
alias dcpull='docker compose pull'
alias dcstart='docker compose start'
alias dck='docker compose kill'

alias als='alias | grep'
alias grep='grep --color=auto'

alias c='clear'
alias t='tmux'
alias h='cauce'
alias e='exit'

alias czp='chezmoi apply'
function czpf
    env CHEZMOI_FORCE_NIX=1 chezmoi apply $argv
end
alias czf='chezmoi apply --include=files'
alias cza='chezmoi add'
function cznixup
    cd ~/.config/nix; and nix flake update; and chezmoi add ~/.config/nix/flake.lock
end
function czbrewup
    cd ~/.config/nix; and nix flake update brew-src; and chezmoi add ~/.config/nix/flake.lock
end
alias czinit='chezmoi init --apply Sirtoolkit'

alias qc-lily='qmk compile -kb lily58 -km my_lily58'
alias qf-lily='qmk flash -kb lily58 -km my_lily58'
alias krun='mise run krun'
alias kkill='mise run kkill'
alias vpn='sudo openvpn --config ~/.config/openvpn/sslvpn-cesar@onetouch.hn-client-config.ovpn --auth-user-pass ~/.config/openvpn/pass.txt'
