-- Auto-generated by Ceryon (theme sync). Safe to delete to opt out.
local state = vim.fn.stdpath("state") .. "/ceryon-theme.lua"
vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    local ok, theme = pcall(dofile, state)
    if ok and type(theme) == "table" and theme.colorscheme then
      vim.o.background = theme.background or "dark"
      pcall(vim.cmd.colorscheme, theme.colorscheme)
    end
  end,
})
return {}
