version: 04b11d4
log:
    path: /tmp/csql.log
    level: info
    prettyPrint: true
editor:
    command: nvim
    env: EDITOR
    enabled: true
ui:
    schemaPanelWidth: 30
    vimMode: true
mcp:
    enabled: true
    port: 0
    allowRead: false
    allowWrite: false
mcpServers:
    - connection: Mongo QA - Pepsichat
      engine: mongo
      port: 9741
      allowRead: true
      allowWrite: false
      enabled: true
security:
    method: keyring
showConnectionPage: true
styles:
    nerdFont: true
    currentStyle: gruvbox.yaml
