source "$HOME/.config/shell/purge/purge_all_mobile_dev_cache.sh"
source "$HOME/.config/shell/purge/purge_config.sh"
source "$HOME/.config/shell/purge/mise_purge_all.sh"
source "$HOME/.config/shell/purge/brew_purge_formula.sh"
source "$HOME/.config/shell/purge/brew_purge_cask.sh"
source "$HOME/.config/shell/purge/mas_purge_all.sh"
source "$HOME/.config/shell/purge/system_log_cleanup.sh"
source "$HOME/.config/shell/purge/purge_all.sh"
