# Opciones generales
set-option -g mouse on
set-option -g status-position top
set-option -g prefix C-a
set-option -wg automatic-rename off

# Ensure shells are login shells to load profile
set-option -g default-command ""
set-option -g default-shell "/bin/zsh"

bind -n S-Enter send-keys Escape "[13;2u"

set -g base-index 1
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 10000
set -g status-left ""
set -g status-right ""

# Opciones de paneles
setw -g pane-base-index 1

# Desvincular prefijo por defecto
unbind C-b

# Atajos de teclado (Keybindings)
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuration reloaded!"

bind-key C-a send-prefix

bind C new-session

# --- Plugins ---
# Gestor de plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'o0th/tmux-nova'

set -g @nova-segments-0-right "whoami"
set -g @nova-status-style-bg "#1d2021"
set -g @nova-status-style-fg "#fbf1c7"
set -g @nova-status-style-active-bg "#8ec07c"
set -g @nova-status-style-active-fg "#32302f"
set -g @nova-segment-whoami-colors "#83a598 #32302f"

# set -g @nova-rows 0
# set -g @nova-nerdfonts true
# set -g @nova-nerdfonts-left 
# set -g @nova-nerdfonts-right 
# set -g @nova-status-style-double-bg "#689d6a"
# set -g @nova-segment-mode-colors "#689d6a #32302f"
# set -g @nova-segments-0-left "mode"

# Iniciar TPM (SIEMPRE AL FINAL)
run '~/.config/tmux/plugins/tpm/tpm'
