onboarding = false
[keys]
prefix = "ctrl+a"
previous_workspace = "f8"
next_workspace = "f9"

previous_agent = "f10"
next_agent = "f11"

[[keys.command]]
key = "prefix+L"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+m"
type = "pane"
command = "mole"

[worktrees]
directory = "~/.herdr/worktrees"

[theme]
name = "gruvbox"

[ui]
mouse_capture = true
confirm_close = false
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true
